server:
  port: 8092

        
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/DemoPlanilla
    username: postgres 
    password: benjamin17


microservicio-a:
         afp: 0.0725
  
microservicio-a:
         isssFijo: 30
         isssSueldo: 0.03
