server:
  port: 8092

 
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream, info, health
        
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/DemoPlanilla
    username: postgres 
    password: benjamin17
