server:
  port: 8092

        
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/DemoPlanilla
    username: postgres 
    password: benjamin17


microservicio-a:
         afp: 0.03
         isssMayor: 30
         isssMenor: 0.03
